# Generated by Django 6.0.7 on 2026-07-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_playlisttrack_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('order', 'playlist'), ('playlist', 'track')},
        ),
    ]
