# Generated by Django 6.0.7 on 2026-07-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_playlisttrack_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='genres',
        ),
    ]
